### ISSUE TITLE
[Bug] SuperGradient: Gradient oversteps Zen's border-radius on content window

### ISSUE THREAD

**Issue by enoversum** [JLBlk/Zen-Themes#14] opened 2024-09-19 21:14 UTC
This is simple to replicate: If SuperGradient is disabled, the outer border of the content window for a website or a settings page is shown correctly. Once you activate a gradient or the Mod, the border-radius of the gradient is overlapping the border, thus creating gaps at the edges of the browser. 

With SuperGradient:
![image](https://github.com/user-attachments/assets/c5f6ea10-a2c7-4b4f-8e89-f1035daa31b9)

Without SuperGradient:
![image](https://github.com/user-attachments/assets/bc4edb99-6b4b-4e91-badd-75f7c68abcc2)

Would be ideal to have the gradients not interfere with the border/border-radius of Zen.

**Comment by JSGRD22** [comment] 2024-09-25 08:44
Issue seems to have resurfaced in 1.0.1-a.5

**Comment by JLBlk** [comment] 2024-09-25 14:59
I already had a solution for that, but removed it since a4 of zen or something fixed it, but it seems you're right that the issue is there again. I'll just implement my solution. -> Will be fixed with the next release
If you don't want to wait until the update is public, you can add the following code to your userChrome.css

```
/* This fixes the corners of the browser content */
:root:not([inDOMFullscreen='true']):not([chromehidden~='location']):not([chromehidden~='toolbar']) {
  & #tabbrowser-tabbox #tabbrowser-tabpanels .browserSidebarContainer {
    overflow: hidden;
  }
}
```

**Closed** 2024-09-30 13:10 UTC
Labels: bug, SuperGradient
