### ISSUE TITLE
[Bug] [Super URL Bar] Bookmarks Star is layered over other icons

### ISSUE THREAD

**Issue by Bout2GitIt** [JLBlk/Zen-Themes#28] opened 2024-10-09 07:38 UTC
**Affected Theme**
 - Super URL Bar
 - Version 1.3.0

**Affected Theme Settings**
-

**Zen Version**: 1.0.1-a.7

**System OS**: MacOS 12.1

**Describe the bug**
The Bookmarks Star fades in on top of other icons, like the Reader Mode icon. This makes it impossible to click the icon underneath (I love the new way the icons fade in, though. Thank you for implementing!)

**To Reproduce**
1. In Super URL Bar settings, click "Hide the Bookmarks (Star) icon"
2. Navigate to a website
3. Hover mouse over the right end of the URL bar

**Expected behavior**
Clicking "Hide the Bookmarks (Star) icon should keep the star from appearing at all.

**Screenshots/Videos**
Here you can see the star layered over Container Tabs, RSS Feed, and Reader Mode, depending on the site.
![Screen Shot 2024-10-09 at 4 33 31 PM](https://github.com/user-attachments/assets/78d6af07-1ee6-4a81-885b-907f06df90c0)

**Comment by JLBlk** [comment] 2024-10-12 15:14
Wow, that's hella weird. Does this also happen on a new profile?, so that it's sure that it isn't due to conflicting css. You're using the hover option (at the bottom) in mod settings, right? The problem is that i can't seem to reproduce it ....
Is there anything else noteworthy that could help me reproduce that?

**Comment by JLBlk** [comment] 2024-10-26 14:34
Since there is no answer, i'll close this now. I suspect that there was other custom css, since this shouldn't be the case with the mod alone and i couldn't reproduce it

**Closed by JLBlk** 2024-10-26 14:34 UTC
Labels: bug, SuperUrlBar
